config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get  'tabattachment',       to: 'tab_attachment#get_all'
  post 'newimage',            to: 'image_tab_attachment#create'
  post 'newlink',             to: 'video_tab_attachment#create'
  post 'newtabtitle',         to: 'tab_attachment#new_tab_title'
  post 'deletetabattachment', to: 'tab_attachment#delete'

  get 'videomask',       to: 'video_attachment#get_video_mask'
  get 'videocustom',     to: 'video_attachment#get_video_custom'
  post 'setmask',        to: 'video_attachment#set_mask'
  post 'setvideomask',   to: 'video_attachment#set_video_mask'
  post 'setvideocustom', to: 'video_attachment#set_video_custom'

  post 'getsliderimg',        to: 'slider_attachment#get_by_kind'
  post 'newsliderimg',        to: 'slider_attachment#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iframe_tab_attachment.rb
class IframeTabAttachment < TabAttachment
end

app/models/image_tab_attachment.rb
class ImageTabAttachment < TabAttachment
  mount_uploader :link, ImageUploader
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/slider_attachment.rb
class SliderAttachment < ApplicationRecord
  mount_uploader :link, SliderUploader
end

app/models/tab_attachment.rb
class TabAttachment < ApplicationRecord
end

app/models/video_attachment.rb
class VideoAttachment < ApplicationRecord
end

app/models/video_tab_attachment.rb
class VideoTabAttachment < TabAttachment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    # @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {})
    end
end

app/controllers/tab_attachment_controller.rb
class TabAttachmentController < ApplicationController
  def get_all
    videoLinks = TabAttachment.where(:type => "VideoTabAttachment")
    imgLinks = TabAttachment.where(:type => "ImageTabAttachment")
    tabAll = videoLinks | imgLinks
    render json: { tabs: tabAll }
  end

  def new_tab_title
    position = params[:position]
    title = params[:title]
    result = find(position)

    result.title = title
    result.save
  end

  def find(pos)
    result = TabAttachment.where(:type => "ImageTabAttachment").find_by(position: pos) || TabAttachment.where(:type => "VideoTabAttachment").find_by(position: pos)

    return result
  end


  def delete
    position = params[:position]
    last = params[:last]

    toDelete = find(position)
    if !toDelete
      return
    end

    toDelete.destroy

    (position+1..last).each do |pos|
      res = find(pos)
      res.position = pos - 1
      res.save
    end

  end

end

app/controllers/video_attachment_controller.rb
class VideoAttachmentController < ApplicationController
  def get_video_mask
    mask = VideoAttachment.find_by(kind: 'mask')
    video = VideoAttachment.find_by(kind: 'videoMask')

    render json: {mask: mask, video: video}
  end

  def set_mask
    mask = params[:mask]
    maskRec = VideoAttachment.find_or_create_by(kind: 'mask')
    maskRec.link = mask

    maskRec.save
  end

  def set_video_mask
    link = params[:link]
    video = VideoAttachment.find_or_create_by(kind: 'videoMask')
    video.link = link

    video.save

    if video.save
      render json: {link: {link:link}}
    end
  end

  def get_video_custom
    video = VideoAttachment.find_by(kind: 'videoCustom')

    render json: {videoCustom: video}
  end

  def set_video_custom
    link = params[:link]
    video = VideoAttachment.find_or_create_by(kind: 'videoCustom')
    video.link = link

    video.save
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/tab_video_helper.rb
module TabVideoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ADC Mediamodules</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>
    <%#= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<%= javascript_pack_tag 'index' %>
<%= javascript_pack_tag 'hello_react' %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>